### ISSUE TITLE
Missing stub: genesis_do_post_title

### ISSUE THREAD

**Issue by claytoncollie** [php-stubs/genesis-stubs#1]
Hi there. I noticed that the stub for the function, `genesis_do_post_title`, is missing but I am not sure why or how to remedy the situation. In my project, I created a stub file and included it in the phpstan.neon. That works fine but I would like to contribute back to this repo if possible. Searching the Genesis codebase reveals that this function has been present since version 1.1.0 so I think it should be included. If you can point me in the right direction, I can make a PR to re-build the stubs files with this function present.

**Comment by szepeviktor** [comment]
Just lay back Clayton.
https://youtu.be/BzerWhLQrew?t=72
When this number ends `genesis_do_post_title` will be included.

**Comment by szepeviktor** [comment]
It is defined in

https://github.com/php-stubs/genesis-stubs/blob/643c34ccf95bb32baca2b15f15a1d04726dd3339/finder.php#L5

but this directory was not included.
